kind: Namespace
apiVersion: v1
metadata:
  name: rag-ai
#--------------------
kind: Deployment
apiVersion: apps/v1
metadata:
  name: open-webui
  namespace: rag-ai
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      namespace: rag-ai
      labels:
        app: open-webui
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        env:
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            memory: 2G
            cpu: 1
          requests:
            memory: 512M
            cpu: 250m
        ports:
        - containerPort: 8080
          protocol: TCP
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: {{port}}
        #     scheme: HTTPS
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: {{port}}
        #     scheme: HTTPS
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
        - name: webui-data
          mountPath: /app/backend/data
      volumes:
      - name: ollama-data
        persistentVolumeClaim:
          claimName: ollama-data
      - name: webui-data
        persistentVolumeClaim:
          claimName: webui-data
