kind: Namespace
apiVersion: v1
metadata:
  name: rag-ai
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: open-webui
  namespace: rag-ai
spec:
  rules:
  - host: open-webui.home.arpa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: open-webui
            port:
              number: 80
---
kind: Service
apiVersion: v1
metadata:
  name: open-webui
  namespace: rag-ai
spec:
  selector:
    app: open-webui
  ports:
  - name: https
    protocol: TCP
    port: 80
    targetPort: 8080
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ollama-data
  namespace: rag-ai
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100G
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: webui-data
  namespace: rag-ai
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10G
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: open-webui
  namespace: rag-ai
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      namespace: rag-ai
      labels:
        app: open-webui
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        env:
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            memory: 2G
            cpu: 1
          requests:
            memory: 512M
            cpu: 250m
        ports:
        - containerPort: 8080
          protocol: TCP
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: {{port}}
        #     scheme: HTTPS
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: {{port}}
        #     scheme: HTTPS
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
        - name: webui-data
          mountPath: /app/backend/data
      volumes:
      - name: ollama-data
        persistentVolumeClaim:
          claimName: ollama-data
      - name: webui-data
        persistentVolumeClaim:
          claimName: webui-data
